@hostname = http://localhost:3000
@controller = messages

GET {{hostname}}/{{controller}}

###

GET {{hostname}}/{{controller}}/12

###

POST {{hostname}}/{{controller}}
Content-Type: application/json

{
    "content": "hi there"
}

###

